sqlite:
  :adapter: sqlite
  :database: spec/acts_as_approvable_plugin.sqlite.db

sqlite3:
  :adapter: sqlite3
  :database: spec/acts_as_approvable_plugin.sqlite3.db

mysql2:
  :adapter: mysql2
  :database: acts_as_approvable_test
  :user: root
